---
# tasks file for roles/webservers

    tasks:
      - name: Upload application file
        copy:
          src: ../files/index.php
          dest: "{{ path_to_app}}"
          mode: 0755
      
      - name: Create simple info page
        copy:
          dest: "{{ path_to_app }}/info.php"
          content: "<h1> Info about our webserver {{ ansible_hostname }} </h1>"
      
      # runs the ls -la command on the path_to_app variable and stores
      # in a variable called dir_contents
      - name: See directory contents
        command: ls -la {{ path_to_app}}
        register: dir_contents

      # displays the contents of the dor_contents variable
      # created in the task above
      - name: Debug directory contents
        debug:
          msg: "{{ dir_contents }}"

# This searches the /etc/php.ini file
# finds the line that says short_open_tag
# and changes it to short_open_tag=On
# notify parameter notifies restart apache there is a change
# to the php.ini file
      - name: configure php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=On'  
        notify: restart apache